# Generated by Django 5.0.7 on 2024-08-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="media/users/avatars/default_avatar.jpg",
                null=True,
                upload_to="media/users/avatars",
                verbose_name="Аватар",
            ),
        ),
    ]
