# Generated by Django 5.0.7 on 2024-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={
                "verbose_name": "Пожертвование",
                "verbose_name_plural": "Пожертвования",
            },
        ),
        migrations.RemoveField(
            model_name="payments",
            name="course",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="date_payment",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="user",
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Cсылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_sum",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите сумму пожертвования",
                verbose_name="Cумма пожертвования",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "наличные"), ("transfer", "перевод")],
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
