# Generated by Django 5.0.7 on 2024-08-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="url",
            field=models.URLField(
                blank=True, max_length=150, null=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="url",
            field=models.URLField(
                blank=True, max_length=150, null=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/course/preview"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/lesson/preview"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="media/lesson/video"
            ),
        ),
    ]
